import { SidebarDemo } from "@/components/ui/SideBarComponent";
import UnderConstruction from "@/components/UnderConstruction";
import { query } from '@/lib/db';
import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes';
import { AuthProvider } from './context/AuthContext';
import "./globals.css";
export const metadata: Metadata = {
  title: "Worth Watching",
  description: "Generated by create next app",
};

export interface Live {
flag: number
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const getstatus = await query<Live>('SELECT flag from UnderConstruction');
  return (
    <html lang="en">
      <body><ThemeProvider attribute="class" defaultTheme="dark">
        {getstatus[0].flag == 1 ?
         (<AuthProvider>
          <SidebarDemo>
            {children}
            </SidebarDemo>
            
            {/* <div className="fixed bottom-0 h-auto bg-indigo-800 w-full items-center justify-center flex"><h1>Copywriti di el toro</h1></div> */}
          </AuthProvider>) :
          <UnderConstruction />}

      </ThemeProvider>
      </body>
    </html>
  );
}
