import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes';
import "./globals.css";
import { SidebarDemo } from "@/components/ui/SideBarComponent";
import { AuthProvider } from './context/AuthContext';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><ThemeProvider attribute="class" defaultTheme="dark"> <AuthProvider>  <SidebarDemo>{children}</SidebarDemo></AuthProvider></ThemeProvider></body>
    </html>
  );
}
