import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes';
import "./globals.css";
import { SidebarDemo } from "@/components/ui/SideBarComponent";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><ThemeProvider attribute="class" defaultTheme="dark">     <SidebarDemo>{children}</SidebarDemo></ThemeProvider></body>
    </html>
  );
}
