import { SidebarDemo } from "@/components/ui/SideBarComponent"
import { Metadata } from "next";



export const metadata: Metadata = {
  title: "Profile - Worth Wathing",
  description: "Generated by create next app",
};
export default function ProfileLayout({
    children, // will be a page or nested layout
  }: {
    children: React.ReactNode
  }) {
    return (
       <section className="flex h-full sm:h-screen mx-auto">
      <div className="absolute top-0 left-0 [background:radial-gradient(125%_125%_at_50%_10%,#0C061C_40%,#180c39_100%)]">
            {children}
          </div>

        </section>

      
    )
  }